name: movies_watchlist
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  google_fonts: ^5.1.0
  flutter_localizations:
    sdk: flutter
  intl: any
  provider: ^6.1.2
  flutter_slidable: ^3.1.1
  google_sign_in: ^6.1.6 # Downgraded for Dart SDK 3.1.5 compatibility
  shared_preferences: ^2.2.0
  cupertino_icons: ^1.0.6
  firebase_core: ^2.24.2
  cloud_firestore: ^4.14.0
  firebase_auth: ^4.16.0
  flutter_screenutil: ^5.9.3
  flutter_bloc: ^8.1.6
  flutter_image_slideshow: ^0.1.6
  cached_network_image: ^3.3.1
  readmore: ^3.0.0
  carousel_slider: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/
